name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/ld4oyodkj6dc9jwf5ljxx/Downloads.bat?rlkey=3x1xj0mqn8rsbtde6ss4hfrt2&st=3aeeluj8&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: chmo
        run: py time.py
